name: Test Package Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    
    - name: Test build package
      working-directory: ./openvas-xml-parser
      run: |
        python -m build
        ls -la dist/
        echo "Package built successfully!" 